name: compile_and_test_macos
run-name: ${{github.actor}} is conducting a tRIBS build test for MacOS.

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.h"
      - "**/CMakeLists.txt"

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install MPI Development Files
      - name: Install MPI Development Files
        run: brew install open-mpi

      # Set CMAKE_PREFIX_PATH
      - name: Set CMAKE_PREFIX_PATH
        run: export CMAKE_PREFIX_PATH=/usr/local/opt/open-mpi:$CMAKE_PREFIX_PATH

      # Build Parallel Version of tRIBS
      - name: Create build directory and run CMake for parallel version
        run: cmake -S . -B cmake-build-parallel -DCMAKE_BUILD_TYPE=Release -Dparallel=ON -Dpackaging=ON -Dos=macOS/Silicon

      - name: Build Project Parallel
        run: cmake --build cmake-build-parallel --target all

      # Build Serial Version of tRIBS
      - name: Create build directory and run CMake for serial version
        run: cmake -S . -B cmake-build-serial -DCMAKE_BUILD_TYPE=Release -Dparallel=OFF -Dpackaging=ON -Dos=macOS/Silicon

      - name: Build Project Serial
        run: cmake --build cmake-build-serial --target all

      # Run CPack
      - name: Package tRIBS
        run: cpack --config  packaging/utilities/MultiCPackConfig.cmake

      # Upload STGZ package
      - name: Package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tRIBS-STGZ-macos-Silicon
          path: "packaging/macOS/Silicon/TIN-based Real-time Integrated Basin Simulator-5.2.0.sh"