name: compile_and_test
run-name: ${{github.actor}} is conducting a tRIBS build test

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.h"
      - "**/CMakeLists.txt"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: [ g++-11 ]
        include:
        
          - os: macos-latest
            compiler: clang
            target: Macos
            
          - os: ubuntu-latest
            compiler: g++-11
            target: Linux


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: download-openmpi
        run: wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
      - name: extract-openmpi
        run: tar -xvf ./openmpi-4.0.2.tar.gz
      - name: configure-openmpi
        run: ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"
      - name: install-openmpi
        run: |
              make -j
              sudo make install

      - name: "Create build directory and run CMake"
        run: cmake -S . -B build  -DCMAKE_BUILD_TYPE=Debug # TODO update to release

      - name: "Build Project" 
        run: cmake --build build --target all 
 
