name: compile_and_test
run-name: ${{github.actor}} is conducting a tRIBS build test

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.h"
      - "**/CMakeLists.txt"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: [ g++-11 ]
        include:
        
          - os: macos-latest
            compiler: clang
            target: Macos
            
          - os: ubuntu-latest
            compiler: g++-11
            target: Linux


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: "Create build directory and run CMake"
        run: cmake -S . -B build  -DCMAKE_BUILD_TYPE=Debug # TODO update to release
      - name: "Build Project" 
        run: cmake --build build --target all 
 
